/**
 * NCT WISH 멤버 정보
 *
 * kprofiles.com, 나무위키, WISH DOLL 관련 기사 등 공개된 정보를 종합해 자체적으로
 * 요약/정리한 데이터입니다. (정보 출처: 나무위키, kprofiles.com, soojib.com 등 —
 * 비영리 팬 프로젝트 용도로 사실 정보를 재정리했습니다.)
 *
 * color/doll/symbol은 SM에서 공개한 공식 WISH DOLL 캐릭터 기준입니다.
 * imageUrl이 있으면 MemberAvatar가 사진을, 없으면 WISH DOLL 이모지를 보여준다.
 */
import sionPhoto from '../assets/members/sion.webp';
import rikuPhoto from '../assets/members/riku.jpg';
import yushiPhoto from '../assets/members/yushi.webp';
import jaeheePhoto from '../assets/members/jaehee.webp';
import ryoPhoto from '../assets/members/ryo.webp';
import sakuyaPhoto from '../assets/members/sakuya.webp';

export const members = [
  {
    id: 'sion',
    stageName: '시온',
    stageNameEn: 'Sion',
    realName: '오시온',
    birthDate: '2002-05-11',
    nationality: '한국',
    hometown: '전남 목포',
    position: '리더, 리드보컬',
    trainingPeriod: '약 4년',
    color: '#A78BFA',
    imageUrl: sionPhoto,
    doll: { name: '시오닝', symbol: '튤립', emoji: '🌷' },
    height: '179cm',
    weight: '57.5kg',
    bloodType: 'O형',
    zodiac: '황소자리',
    chineseZodiac: '말띠',
    mbti: 'INTJ-A',
    dorm: '1인실',
    hobby: '독서, 애니메이션·드라마 감상, 볼링',
    roleModel: 'EXO 카이',
    favoriteSong: 'NCT "We Go Up"',
    funFacts: [
      '팀의 리더이자 리드보컬을 맡고 있다.',
      '2023년 6월 28일 미래 NCT 멤버로 처음 소개됐다.',
      '동생이 한 명 있다(2004년생).',
      '스스로를 "물"에 비유해 표현한 적이 있다.',
      '어릴 땐 베이스 기타, 지금은 드럼을 즐겨 연주한다.',
      '가수가 아니었다면 모델을 하고 싶다고 밝혔다.',
      '팬들과 소통하기 위해 여러 언어를 배우고 싶어한다.',
      'WISH DOLL 캐릭터 "시오닝"은 보라색 튤립을 모티프로 한다.',
    ],
    bio: '전남 목포 출신으로 약 4년간 SM에서 연습생 생활을 거친 뒤 NCT WISH의 리더 겸 리드보컬로 데뷔했다. 신중하고 합리적이면서도 유머러스한 성격으로 알려져 있으며, 독서와 애니메이션, 드럼 연주를 좋아하는 팀의 맏형 리더.',
  },
  {
    id: 'riku',
    stageName: '리쿠',
    stageNameEn: 'Riku',
    realName: '마에다 리쿠',
    birthDate: '2003-06-28',
    nationality: '일본',
    hometown: '일본 후쿠이',
    position: '메인 래퍼',
    trainingPeriod: '약 1년',
    color: '#EF5350',
    imageUrl: rikuPhoto,
    doll: { name: '쿠리', symbol: '다람쥐', emoji: '🐿️' },
    height: '175.8cm',
    weight: '59.6kg',
    bloodType: 'AB형',
    zodiac: '게자리',
    chineseZodiac: '양띠',
    mbti: 'ISFP',
    dorm: '1인실',
    hobby: '애니메이션·영화 감상',
    roleModel: 'NCT 마크',
    favoriteSong: 'NCT "We Go Up"',
    funFacts: [
      '서바이벌 프로그램 NCT Universe: LASTART에서 가장 먼저 소개된 참가자였다.',
      '누나가 두 명 있다(1998년생, 2001년생).',
      '별명은 쿠리(밤)이며, 보조개가 매력 포인트로 꼽힌다.',
      '소중한 사람에게 받은 편지를 소중히 간직한다.',
      '가수가 아니었다면 빵집에서 일하고 싶다고 밝혔다.',
      '스스로를 "인내심 있는 사람"이라 표현한다.',
      'WISH DOLL 캐릭터 "쿠리"는 빨간색 다람쥐 모티프다.',
    ],
    bio: '일본 후쿠이 출신으로 비교적 짧은 약 1년의 연습생 기간을 거쳐 NCT WISH의 메인 래퍼로 데뷔했다. 서바이벌 프로그램에서 가장 먼저 소개된 멤버로, 인내심 있는 성격과 보조개가 매력 포인트다.',
  },
  {
    id: 'yushi',
    stageName: '유우시',
    stageNameEn: 'Yushi',
    realName: '토쿠노 유우시',
    gatewayBlurb: '그냥 느껴라.',
    birthDate: '2004-04-05',
    nationality: '일본',
    hometown: '일본 도쿄',
    position: '메인 댄서',
    trainingPeriod: '약 7년',
    color: '#4FC3F7',
    imageUrl: yushiPhoto,
    doll: { name: '버블냥', symbol: '고양이 × 물범(버블티 콘셉트)', emoji: '🐱' },
    height: '175cm',
    weight: '59.8kg',
    bloodType: 'A형',
    zodiac: '양자리',
    chineseZodiac: '원숭이띠',
    mbti: 'ESFJ-A',
    dorm: '재희와 2인실',
    hobby: '축구, 닌텐도 스위치(젤다의 전설)',
    roleModel: 'EXO 카이',
    favoriteSong: '-',
    funFacts: [
      '2023년 6월 28일 미래 NCT 멤버로 처음 소개됐다.',
      '데뷔 전 EDAMAME BEANS라는 팀에서 보컬로 활동한 이력이 있다.',
      '연습생 기간이 멤버 중 가장 길다(약 7년).',
      '2016년 초등학교 6학년 때 방학마다 한국을 오가며 훈련을 받다가, 2018년경부터 한국으로 완전히 이주해 정착했다. 실질적으로 한국에서 지낸 기간만 약 8년에 달한다.',
      '남동생이 한 명 있다.',
      '멤버 중 매운 음식을 가장 잘 먹고, 라면을 특히 좋아한다.',
      '너무 기쁘거나 감정이 벅차면 쉽게 눈물을 흘린다.',
      '좋아하는 색은 흰색과 하늘색이다.',
      'WISH DOLL 캐릭터 "버블냥"은 귀를 가리면 물범처럼 보이는 재미있는 디테일이 있다.',
    ],
    bio: '일본 도쿄 출신으로 약 7년이라는 긴 연습생 기간을 거쳤다. 데뷔 전 EDAMAME BEANS 멤버로 활동한 이력이 있으며, 팀의 메인 댄서를 맡고 있다. 차분하면서도 장난기 있는 성격으로, 축구와 게임을 좋아한다.',
  },
  {
    id: 'jaehee',
    stageName: '재희',
    stageNameEn: 'Jaehee',
    realName: '김대영',
    birthDate: '2005-06-21',
    nationality: '한국',
    hometown: '대구',
    position: '메인보컬',
    trainingPeriod: '약 3개월',
    color: '#66BB6A',
    imageUrl: jaeheePhoto,
    doll: { name: '댕트리버', symbol: '나무 모양 꼬리를 가진 리트리버', emoji: '🌳' },
    height: '185cm',
    weight: '67kg',
    bloodType: 'O형',
    zodiac: '쌍둥이자리',
    chineseZodiac: '닭띠',
    mbti: 'ENFP-T',
    dorm: '유우시와 2인실',
    hobby: '노래 연습, 피아노, 독서',
    roleModel: '규현, 진영, 재현(모두 SM 선배)',
    favoriteSong: 'NCT 127 "AY-YO"',
    funFacts: [
      '멤버 중 연습생 기간이 가장 짧다(약 3개월).',
      '형이 두 명 있다(1994년생, 1998년생).',
      '별명은 "댕"(강아지 같다는 의미).',
      '탄탄한 고음과 팔세토가 특기로 꼽힌다.',
      'NCT 127의 "AY-YO" 무대를 보고 아이돌을 꿈꾸게 됐다.',
      '좌우명은 "그럼에도 불구하고"다.',
      '가수가 아니었다면 역사 선생님이 되고 싶다고 밝혔다.',
      'WISH DOLL 캐릭터 이름 "댕트리버"는 본명(대영)의 "댕"과 리트리버를 합친 이름이다.',
    ],
    bio: '대구 출신으로 멤버 중 가장 짧은 약 3개월의 연습생 기간을 거쳐 데뷔했다. 탄탄한 고음과 팔세토가 특기인 팀의 메인보컬로, "그럼에도 불구하고"를 좌우명으로 삼고 있다.',
  },
  {
    id: 'ryo',
    stageName: '료',
    stageNameEn: 'Ryo',
    realName: '히로세 료',
    birthDate: '2007-08-04',
    nationality: '일본',
    hometown: '일본 교토',
    position: '서브보컬',
    trainingPeriod: '약 1년',
    color: '#FFCA28',
    imageUrl: ryoPhoto,
    doll: { name: '론론', symbol: '강아지', emoji: '🐶' },
    height: '165.4cm',
    weight: '52.4kg',
    bloodType: 'A형',
    zodiac: '사자자리',
    chineseZodiac: '돼지띠',
    mbti: 'ENTP-A',
    dorm: '사쿠야와 2인실',
    hobby: '영화 감상, 그림 그리기',
    roleModel: 'NCT 도영, 해찬',
    favoriteSong: 'NCT "Love Sign"',
    funFacts: [
      '누나가 한 명 있다(2004년생).',
      '사쿠야와 절친한 사이로 잘 알려져 있다.',
      'SM 소속 가수들을 좋아하다가 도영을 보고 첫눈에 반해 아이돌을 꿈꿨다.',
      '가장 좋아하는 계절은 봄이다.',
      '가수가 아니었다면 우주비행사가 되고 싶다고 밝혔다.',
      'WISH DOLL 캐릭터 "론론"은 료가 어릴 적 좋아했던 인형 "톤톤"에서 모티프를 따왔다.',
    ],
    bio: '일본 교토 출신으로, 영화 감상과 그림 그리기를 좋아한다. 사쿠야와 절친한 사이로 알려져 있으며, 팀의 서브보컬을 맡고 있다. 활발한 성격에 스스로를 "행복" 그 자체라 표현한 적이 있다.',
  },
  {
    id: 'sakuya',
    stageName: '사쿠야',
    stageNameEn: 'Sakuya',
    realName: '후지나가 사쿠야',
    birthDate: '2007-11-18',
    nationality: '일본',
    hometown: '일본 사이타마',
    position: '리드래퍼, 서브보컬, 막내',
    trainingPeriod: '약 1년',
    color: '#F06292',
    imageUrl: sakuyaPhoto,
    doll: { name: '팡이', symbol: '별 모양 날개를 가진 빵', emoji: '🥐' },
    height: '176cm',
    weight: '57.5kg',
    bloodType: 'AB형',
    zodiac: '전갈자리',
    chineseZodiac: '돼지띠',
    mbti: 'ENFP',
    dorm: '료와 2인실',
    hobby: '쇼핑, 사진 촬영, 축구',
    roleModel: 'NCT 태용',
    favoriteSong: 'NCT "Dancing In The Rain"',
    funFacts: [
      '팀의 막내이자 빵을 매우 좋아하는 것으로 유명하며, 특히 크루아상을 좋아한다.',
      '료와 절친한 사이로 알려져 있다.',
      '매운 음식을 잘 못 먹어 떡볶이도 피한다.',
      '부모님이 K-POP 팬이었던 영향으로 가수의 꿈을 키웠다.',
      '가수가 아니었다면 수영선수가 되고 싶다고 밝혔다.',
      'WISH DOLL 캐릭터 "팡이"는 사쿠야가 좋아하는 빵 + 별 모양 날개 콘셉트다.',
    ],
    bio: '일본 사이타마 출신으로 팀의 막내를 맡고 있다. 빵을 매우 좋아하고 쇼핑과 사진 촬영이 취미이며, 료와 절친한 사이로 알려져 있다. 호기심 많은 성격이 특징.',
  },
];

/**
 * 그룹 공통 정보
 */
export const groupInfo = {
  debutDate: '2024-02-21',
  agency: 'SM엔터테인먼트',
  formation: '서바이벌 프로그램 NCT Universe: LASTART를 통해 결성',
  fandomName: 'NCTzen (엔시즌)',
  officialColor: 'Pearl Neo Champagne',
  greeting: '안녕하세요, NCT WISH입니다.',
};
